In [2]:
import numpy as np

np.__version__

'1.23.5'

# Пример по задаче 1

In [11]:
vec01 = np.arange(1, 10, dtype='int32')
matrix_01 = vec01.reshape(3,3)
matrix_01

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
matrix_02 = matrix_01.transpose()
matrix_02

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
test_concat = 4*matrix_02 + 7*matrix_01
test_concat

array([[11, 30, 49],
       [36, 55, 74],
       [61, 80, 99]])

In [18]:
matrix_by_matrix = np.matrix('5 7; 3 9; 9 1')
matrix_by_matrix + 6

matrix([[11, 13],
        [ 9, 15],
        [15,  7]])

In [25]:
matrix_by_matrix_02 = np.matrix('8 9 12; 6 3 8')
print(matrix_by_matrix_02)
# matrix_changed_02 = matrix_by_matrix_02.tranpose()
# print(matrix_changed_02)

matrix_changed_02 = np.asarray(matrix_by_matrix_02).transpose()

[[ 8  9 12]
 [ 6  3  8]]


In [27]:
test_concat = 4*matrix_by_matrix + 7*matrix_changed_02
test_concat

matrix([[ 76,  70],
        [ 75,  57],
        [120,  60]])

# Пример по задаче 2

In [38]:
# сгенерируем массив из 0
matrix_zeros = np.zeros((16,16), dtype='int32')

In [40]:
matrix_zeros[:, 2] = 4
matrix_zeros

array([[0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
matrix_zeros[4, :] = 3
matrix_zeros

array([[0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [43]:
matrix_zeros[1, 1] = 9
matrix_zeros

array([[0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 9, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [48]:
# сгенерируем массив из 0
matrix_zeros_02 = np.zeros((16,16), dtype='int32')

In [50]:
matrix_zeros_02[::2, 1:4] = 2
matrix_zeros_02[::2, 8:11] = 2
matrix_zeros_02[1::2, :3] = 1
matrix_zeros_02[1::2, 7:10] = 1
matrix_zeros_02

array([[0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0]])

In [51]:
# сгенерируем массив из 0
matrix_zeros_03 = np.zeros((16,16), dtype='int32')

In [53]:
matrix_zeros_03[0::2, ::2] = 9
matrix_zeros_03[1::2, 1::2] = 9
matrix_zeros_03

array([[9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0],
       [0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9],
       [9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0],
       [0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9],
       [9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0],
       [0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9],
       [9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0],
       [0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9],
       [9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0],
       [0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9],
       [9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0],
       [0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9],
       [9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0],
       [0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9],
       [9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0],
       [0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9]])

In [56]:
# сгенерируем массив из 0
matrix_zeros_04 = np.zeros((11,11), dtype='int32')
matrix_zeros_04

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [57]:
matrix_zeros_04[:, 1:4] = 5
matrix_zeros_04

array([[0, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
matrix_zeros_05 = np.zeros((11,11), dtype='int32')
matrix_zeros_05

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [59]:
matrix_zeros_05[7, 3] = 15
matrix_zeros_05

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 15,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [71]:
matrix_zeros_05[8, :-1] = 12
matrix_zeros_05[2, :-5] = 12
matrix_zeros_05

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [12, 12, 12, 12, 12, 12, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 15,  0,  0,  0,  0,  0,  0,  0],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [73]:
matrix_zeros_05[0, -1] = 345
matrix_zeros_05

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 345],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 12,  12,  12,  12,  12,  12,  12,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  15,   0,   0,   0,   0,   0,   0,   0],
       [ 12,  12,  12,  12,  12,  12,  12,  12,  12,  12,  12],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

# Пример задача 3

In [2]:
import numpy as np

In [21]:
vec01 = np.arange(2, 51, step=9.6, dtype="float") #генеририем от 0
print(vec01)
print(vec01.shape)
print(vec01.size)

[ 2.  11.6 21.2 30.8 40.4 50. ]
(6,)
6


In [22]:
gen_sequence, step = np.linspace(2, 50, num=6, dtype="float", retstep=True)
print(gen_sequence)
print(gen_sequence.shape)
print(gen_sequence.size)
print(step)

[ 2.  11.6 21.2 30.8 40.4 50. ]
(6,)
6
9.6


In [23]:
gen_sequence.reshape(2,3)

array([[ 2. , 11.6, 21.2],
       [30.8, 40.4, 50. ]])

In [24]:
gen_sequence01 = np.linspace(1, 24, 24, dtype='int')
print(gen_sequence01)

test01 = gen_sequence01.reshape(12,2)
print(test01)

gen_sequence02 = np.linspace(0, 2.5, 6, dtype='float')
test02 = gen_sequence02.reshape(2,3)
print(test02)
print(gen_sequence02)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
[[0.  0.5 1. ]
 [1.5 2.  2.5]]
[0.  0.5 1.  1.5 2.  2.5]


In [25]:
np.asarray(test01) * np.asarray(test02) # будет ошибка из-за размерности матриц

ValueError: operands could not be broadcast together with shapes (12,2) (2,3) 

In [26]:
test03 = test01[0:3].transpose()
test03

array([[1, 3, 5],
       [2, 4, 6]])

In [27]:
test03 * test02

array([[ 0. ,  1.5,  5. ],
       [ 3. ,  8. , 15. ]])

In [28]:
test01.dot(test02) 

array([[ 3. ,  4.5,  6. ],
       [ 6. ,  9.5, 13. ],
       [ 9. , 14.5, 20. ],
       [12. , 19.5, 27. ],
       [15. , 24.5, 34. ],
       [18. , 29.5, 41. ],
       [21. , 34.5, 48. ],
       [24. , 39.5, 55. ],
       [27. , 44.5, 62. ],
       [30. , 49.5, 69. ],
       [33. , 54.5, 76. ],
       [36. , 59.5, 83. ]])

In [30]:
test05 = np.matmul(test01, test02)
test05

array([[ 3. ,  4.5,  6. ],
       [ 6. ,  9.5, 13. ],
       [ 9. , 14.5, 20. ],
       [12. , 19.5, 27. ],
       [15. , 24.5, 34. ],
       [18. , 29.5, 41. ],
       [21. , 34.5, 48. ],
       [24. , 39.5, 55. ],
       [27. , 44.5, 62. ],
       [30. , 49.5, 69. ],
       [33. , 54.5, 76. ],
       [36. , 59.5, 83. ]])

In [34]:
print(test05 % 5)
print(test05 % 5 == 0)

[[3.  4.5 1. ]
 [1.  4.5 3. ]
 [4.  4.5 0. ]
 [2.  4.5 2. ]
 [0.  4.5 4. ]
 [3.  4.5 1. ]
 [1.  4.5 3. ]
 [4.  4.5 0. ]
 [2.  4.5 2. ]
 [0.  4.5 4. ]
 [3.  4.5 1. ]
 [1.  4.5 3. ]]
[[False False False]
 [False False False]
 [False False  True]
 [False False False]
 [ True False False]
 [False False False]
 [False False False]
 [False False  True]
 [False False False]
 [ True False False]
 [False False False]
 [False False False]]


In [35]:
test05[test05 % 5 == 0]

array([20., 15., 55., 30.])

In [40]:
vec1 = np.arange(start=0, stop=1.5, step=0.1, dtype='float')
vec1 = vec1.reshape(5, 3)
vec2 = np.arange(start=1, stop=7, step=1, dtype='int64')
vec2 = vec2.reshape(6, 1)
print(vec1.dot(vec2))
print(np.matmul(vec1, vec2))
print(vec1.dot(vec2))

ValueError: shapes (5,3) and (6,1) not aligned: 3 (dim 1) != 6 (dim 0)