In [3]:
matrix_zeros = np.zeros((16, 16))
print(matrix_zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [2]:
import numpy as np

In [4]:
matrix_zeros[0::2, ::2] = 9
matrix_zeros[1::2, 1::2] = 9
print(matrix_zeros)

[[9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0.]
 [0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9.]
 [9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0.]
 [0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9.]
 [9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0.]
 [0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9.]
 [9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0.]
 [0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9.]
 [9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0.]
 [0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9.]
 [9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0.]
 [0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9.]
 [9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0.]
 [0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9.]
 [9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0.]
 [0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9. 0. 9.]]


In [5]:
vec01 = np.arange(2.7, step=0.5,dtype='float')
vec01

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [6]:
vec02 = np.arange(1, 10, dtype='int')
print(vec02)

[1 2 3 4 5 6 7 8 9]


In [12]:
matrix_from_vec01 = vec01.reshape(2, 3)
print(matrix_from_vec01)

matrix_from_vec02 = vec02.reshape(3, 3)
print(matrix_from_vec02)

[[0.  0.5 1. ]
 [1.5 2.  2.5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
tranpose_matrix = np.transpose(matrix_from_vec01)
tranpose_matrix

array([[0. , 1.5],
       [0.5, 2. ],
       [1. , 2.5]])

In [46]:
test = matrix_from_vec01.reshape(6, 1)
print(test)
print(test.strides)
print(test.shape)

tranpose = np.transpose(test, (0,1))
tranpose_test = np.transpose(test, (1,0))
print(tranpose)
print(tranpose_test)
# tranpose_matrix01 = np.transpose(matrix_from_vec01, (0, 1, 6))
# tranpose_matrix01

[[0. ]
 [0.5]
 [1. ]
 [1.5]
 [2. ]
 [2.5]]
(8, 8)
(6, 1)
[[0. ]
 [0.5]
 [1. ]
 [1.5]
 [2. ]
 [2.5]]
[[0.  0.5 1.  1.5 2.  2.5]]


In [9]:
matrix_from_vec01 + matrix_from_vec02

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 